config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]
  resources :tags, only: :show, param: :alias
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true
  has_and_belongs_to_many :tags

  validates :text, :user, presence: true
  validates :text, length: { maximum: 255 }

  strip_attributes only: [:text, :answer]

  after_commit :destroy_unused_tags

  private

  def destroy_unused_tags
    Tag.left_outer_joins(:questions).where(questions: { id: nil }).destroy_all
  end

  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:edit, :update, :destroy]
  before_action :authorize_user, except: [:create]

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.author = current_user if current_user
    @question.ip = request.remote_ip

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: I18n.t('controllers.questions.created')
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: I18n.t('controllers.questions.updated')
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy

    redirect_to user_path(user), notice: I18n.t('controllers.questions.destroyed')
  end

  private

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    if current_user.present? && params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end

  def check_captcha(model)
    if current_user.present?
      true
    else
      verify_recaptcha(model: model)
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
.form
  =form_for @question, html: {id: 'invisible-recaptcha-form'} do |f|
    -if @question.errors.any?
      .form-errors
        ul
          -@question.errors.full_messages.each do |message|
            li.form-error-message = message

    =f.hidden_field :user_id

    .form-field
      =f.label :text, class: 'form-label'
      =f.text_area :text, class: 'form-textarea'

    -if is_current_user?(@question.user)
      .form-field
        =f.label :answer, class: 'form-label'
        =f.text_area :answer, class: 'form-textarea'

    .form-action.buffer-both
      -if current_user.present?
        = f.submit t('.save'), class: 'button button-dark button-small'
      -else
        = invisible_recaptcha_tags callback: 'submitInvisibleRecaptchaForm', text: t('.save'), class: 'button button-dark button-small'

      = t('.alt')
      =link_to t('.back'), user_path(@question.user)

app/views/questions/_question.html.slim
- question ||= nil
- action_icon = question.answer.blank? ? 'reply' : 'pencil'

.question id="question_#{question.id}"
  .question-content
    .question-text.text-lead
      = fill_text_with_tag_links(question.text, question.tags)

    - if question.answer.present?
      .question-answer.text-lead
        = fill_text_with_tag_links(question.answer, question.tags) if question.answer.present?

    .question-author
      -if question.author.present?
        = link_to_unless_current user_nickname(question.author), user_path(question.author)
      -else
        i
          = t('.anonymous')
          - if question.ip
            - city = city_name(question.ip)
            = " (#{city})" if city.present?
    .question-date
      = I18n.l(question.created_at, format: :short)

  - if is_current_user?(question.user)
    .question-actions
      = link_to fa_icon(action_icon), edit_question_path(question)
      = link_to fa_icon('trash-o'), question_path(question),
                method: :delete, data: {confirm: t('.confirm_destroy')}

app/views/questions/_tagged_question.html.slim
.tagged-question
  = t('.question_for')
  = link_to user_nickname(question.user), user_path(question.user)
  = ' '
  = link_to t('.jump_to_question'), "#{user_path(question.user)}#question_#{question.id}"
  = render(partial: 'questions/question', object: question)

app/views/questions/create.js.erb
$(".questions-list").prepend("<%= j render 'questions/question', question: @question %>");
$(".user-statistics").html("<%= j render 'users/user_statistics', user: @question.user %>");
$("#question_text").val('');

app/views/questions/destroy.js.erb
$("#question_<%= @question.id %>").remove();
$('.user-statistics').html("<%= j render 'users/user_statistics', user: @question.user %>");

app/views/questions/edit.html.slim
.container.content-wrapper.buffer-both
  h1.title-medium = t('activerecord.models.question')

  .column-1-2
    = render 'form'